# Generated by Django 4.0.4 on 2022-07-17 23:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('description_short', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('book_address', models.CharField(blank=True, max_length=500, null=True)),
                ('book_genre', multiselectfield.db.fields.MultiSelectField(choices=[('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('ScienceFiction', 'Sciencefiction'), ('Biography', 'Biography'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Suspense', 'Suspense'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Graphic', 'Graphic'), ('Short', 'Short'), ('AutoBiography', 'Autobiography'), ('Food', 'Food'), ('Drink', 'Drink'), ('Art', 'Art'), ('History', 'History'), ('TrueCrime', 'Truecrime'), ('Travel', 'Travel'), ('Humor', 'Humor'), ('Science', 'Science'), ('Technology', 'Technology'), ('Dystopian', 'Dystopian'), ('Photography', 'Photography')], max_length=216)),
                ('book_category', multiselectfield.db.fields.MultiSelectField(choices=[('Fiction', 'Fiction'), ('NonFiction', 'Nonfiction'), ('Comic', 'Comic')], max_length=24)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('secret_access_code', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
